filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["192.168.43.46:5044"]

setup.kibana.host: "192.168.43.46:5601"

filebeat.inputs:
  - type: log
    paths:
      - "/var/log/lib-log/*.log"
    json.message_key: log
    json.keys_under_root: true
    processors:
      - add_docker_metadata: ~

setup.dashboards.enabled: false
