version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.28
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db:/tmp/test
    networks:
      - backend

  library-backend:
    depends_on:
      - mysqldb
    build: ./Backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - GMAIL= $GMAIL
      - GMAIL_PASS= $GMAIL_PASS
      - CLOUDINARY_NAME=$CLOUDINARY_NAME
      - CLOUDINARY_KEY=$CLOUDINARY_KEY
      - CLOUDINARY_SECRET=$CLOUDINARY_SECRET
    networks:
      - backend
      - frontend

  library-frontend:
    depends_on:
      - library-backend
    build:
      context: ./Frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - frontend

volumes:
  db:
networks:
  backend:
  frontend:
